### ISSUE TITLE
gh: permission error

### ISSUE THREAD

**Issue by mahowi** [donnemartin/gitsome#106]
I have installed gitsome 0.6.0 via pip3 on Raspbian. Whenever I start gh as normal user I get a permission error:
```
pi@raspberrypi:~ $ gh
Traceback (most recent call last):
  File "/usr/local/bin/gh", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2888, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 758, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2888, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2425, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2415, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1413, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1410, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1514, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/protobuf-3.2.0rc1-py3.4.egg/EGG-INFO/namespace_packages.txt'
```

```
pi@raspberrypi:~ $ ls -la /usr/local/lib/python3.4/dist-packages/protobuf-3.2.0rc1-py3.4.egg/EGG-INFO/namespace_packages.txt
-rw-r----- 1 root staff 7 Jan 16 12:16 /usr/local/lib/python3.4/dist-packages/protobuf-3.2.0rc1-py3.4.egg/EGG-INFO/namespace_packages.txt
```

Works, when I *chmod 666 namespace_packages.txt*.

**Comment by donnemartin** [comment]
Thanks for the report!
