### ISSUE TITLE
gh: Trending reporting error 

### ISSUE THREAD

**Issue by RupGautam** [donnemartin/gitsome#107]
Trying to pull trending topics and I got that error. 
```
Listing daily trending all repos...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/feedparser.py", line 399, in __getattr__
    return self.__getitem__(key)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/feedparser.py", line 348, in __getitem__
    return dict.__getitem__(self, 'updated_parsed')
KeyError: 'updated_parsed'```


```
System info: 

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by donnemartin** [comment]
Thanks for filing the issue, I can also reproduce it.  Seems the GitHub Trends RSS data format has changed and is causing the issue.
