### ISSUE TITLE
ValueError when using gh pull-requests on github enterprise.

### ISSUE THREAD

**Issue by milin** [donnemartin/gitsome#109]
``` 
❯ gh pull-requests
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/gitsome/bin/gh", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/gitsome/main_cli.py", line 26, in cli
    github.cli()
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/gitsome/githubcli.py", line 555, in pull_requests
    github.pull_requests(limit, pager)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/gitsome/github.py", line 86, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/gitsome/lib/python3.5/site-packages/gitsome/github.py", line 558, in pull_requests
    user, repo, issues, number = url.split('/')
ValueError: too many values to unpack (expected 4)
```

**Comment by donnemartin** [comment]
Hi @milin, thanks for the report!  

I see this working on my end without using GH Enterprise.  Could you verify if this is an Enterprise-only issue?

**Comment by milin** [comment]
I can reproduce this always when using it with gh enterprise. Let me try it with gh and see if i can reproduce.

**Comment by milin** [comment]
` gh pull-requests` works without any issues pointing to github. Looks like it's only an issue with github enterprise.

**Comment by donnemartin** [comment]
Thanks confirming this is a GH Enterprise issue!
