### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Vinoth7** [donnemartin/gitsome#110]
Hi Guys, 
I am so impressed about the gitsome and its capabilities. Eager to use it but having issues with installation. Installed Phyton(3.6) and ran below command with sudo and with out sudo but getting the below error. Any help would be appreciated.

**_Phyton Version_** 
```
vinoth @ ~  → pip3 -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
```
**_Gitsome Installation_**
```
vinoth @ ~  → pip3 install gitsome
Collecting gitsome
  Using cached gitsome-0.6.0.tar.gz
Requirement already satisfied: numpydoc<1.0,>=0.5 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: ply<4.0,>=3.4 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: prompt-toolkit<1.1.0,>=1.0.0 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: requests<3.0.0,>=2.8.1 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: colorama<1.0.0,>=0.3.3 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: click<7.0,>=5.1 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: feedparser<6.0.0,>=5.2.1 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: pytz<2017.0,>=2016.3 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: docopt<1.0.0,>=0.6.2 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: uritemplate.py<1.0.0,>=0.2.0 in /usr/local/lib/python3.6/site-packages (from gitsome)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/site-packages (from prompt-toolkit<1.1.0,>=1.0.0->gitsome)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prompt-toolkit<1.1.0,>=1.0.0->gitsome)
Building wheels for collected packages: gitsome
  Running setup.py bdist_wheel for gitsome ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/tmpb4owwoqxpip-wheel- --python-tag cp36:

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/gitsome
  copying gitsome/__init__.py -> build/lib/gitsome
  copying gitsome/compat.py -> build/lib/gitsome
  copying gitsome/completer.py -> build/lib/gitsome
  copying gitsome/completions.py -> build/lib/gitsome
  copying gitsome/completions_git.py -> build/lib/gitsome
  copying gitsome/config.py -> build/lib/gitsome
  copying gitsome/formatter.py -> build/lib/gitsome
  copying gitsome/github.py -> build/lib/gitsome
  copying gitsome/githubcli.py -> build/lib/gitsome
  copying gitsome/main.py -> build/lib/gitsome
  copying gitsome/main_cli.py -> build/lib/gitsome
  copying gitsome/parser_table.py -> build/lib/gitsome
  copying gitsome/rss_feed.py -> build/lib/gitsome
  copying gitsome/table.py -> build/lib/gitsome
  copying gitsome/utils.py -> build/lib/gitsome
  copying gitsome/view_entry.py -> build/lib/gitsome
  copying gitsome/web_viewer.py -> build/lib/gitsome
  creating build/lib/tests
  copying tests/__init__.py -> build/lib/tests
  copying tests/compat.py -> build/lib/tests
  copying tests/mock_feed_parser.py -> build/lib/tests
  copying tests/mock_github_api.py -> build/lib/tests
  copying tests/mock_pretty_date_time.py -> build/lib/tests
  copying tests/run_tests.py -> build/lib/tests
  copying tests/test_completer.py -> build/lib/tests
  copying tests/test_config.py -> build/lib/tests
  copying tests/test_github.py -> build/lib/tests
  copying tests/test_github_cli.py -> build/lib/tests
  copying tests/test_web_viewer.py -> build/lib/tests
  creating build/lib/xonsh
  copying xonsh/__init__.py -> build/lib/xonsh
  copying xonsh/aliases.py -> build/lib/xonsh
  copying xonsh/ast.py -> build/lib/xonsh
  copying xonsh/base_shell.py -> build/lib/xonsh
  copying xonsh/built_ins.py -> build/lib/xonsh
  copying xonsh/completer.py -> build/lib/xonsh
  copying xonsh/diff_history.py -> build/lib/xonsh
  copying xonsh/dirstack.py -> build/lib/xonsh
  copying xonsh/environ.py -> build/lib/xonsh
  copying xonsh/execer.py -> build/lib/xonsh
  copying xonsh/foreign_shells.py -> build/lib/xonsh
  copying xonsh/history.py -> build/lib/xonsh
  copying xonsh/imphooks.py -> build/lib/xonsh
  copying xonsh/inspectors.py -> build/lib/xonsh
  copying xonsh/jobs.py -> build/lib/xonsh
  copying xonsh/lazyjson.py -> build/lib/xonsh
  copying xonsh/lexer.py -> build/lib/xonsh
  copying xonsh/main.py -> build/lib/xonsh
  copying xonsh/openpy.py -> build/lib/xonsh
  copying xonsh/parser.py -> build/lib/xonsh
  copying xonsh/parser_table.py -> build/lib/xonsh
  copying xonsh/pretty.py -> build/lib/xonsh
  copying xonsh/proc.py -> build/lib/xonsh
  copying xonsh/prompt_toolkit_completer.py -> build/lib/xonsh
  copying xonsh/prompt_toolkit_history.py -> build/lib/xonsh
  copying xonsh/prompt_toolkit_key_bindings.py -> build/lib/xonsh
  copying xonsh/prompt_toolkit_shell.py -> build/lib/xonsh
  copying xonsh/pyghooks.py -> build/lib/xonsh
  copying xonsh/readline_shell.py -> build/lib/xonsh
  copying xonsh/replay.py -> build/lib/xonsh
  copying xonsh/shell.py -> build/lib/xonsh
  copying xonsh/teepty.py -> build/lib/xonsh
  copying xonsh/timings.py -> build/lib/xonsh
  copying xonsh/tools.py -> build/lib/xonsh
  creating build/lib/gitsome/lib
  copying gitsome/lib/__init__.py -> build/lib/gitsome/lib
  copying gitsome/lib/debug_timer.py -> build/lib/gitsome/lib
  copying gitsome/lib/pretty_date_time.py -> build/lib/gitsome/lib
  creating build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/__about__.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/__init__.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/api.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/auths.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/decorators.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/events.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/exceptions.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/git.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/github.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/licenses.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/models.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/notifications.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/null.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/orgs.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/pulls.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/session.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/structs.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/users.py -> build/lib/gitsome/lib/github3
  copying gitsome/lib/github3/utils.py -> build/lib/gitsome/lib/github3
  creating build/lib/gitsome/lib/html2text
  copying gitsome/lib/html2text/__init__.py -> build/lib/gitsome/lib/html2text
  copying gitsome/lib/html2text/html2text.py -> build/lib/gitsome/lib/html2text
  creating build/lib/gitsome/lib/img2txt
  copying gitsome/lib/img2txt/__init__.py -> build/lib/gitsome/lib/img2txt
  copying gitsome/lib/img2txt/img2txt.py -> build/lib/gitsome/lib/img2txt
  creating build/lib/gitsome/lib/github3/gists
  copying gitsome/lib/github3/gists/__init__.py -> build/lib/gitsome/lib/github3/gists
  copying gitsome/lib/github3/gists/comment.py -> build/lib/gitsome/lib/github3/gists
  copying gitsome/lib/github3/gists/file.py -> build/lib/gitsome/lib/github3/gists
  copying gitsome/lib/github3/gists/gist.py -> build/lib/gitsome/lib/github3/gists
  copying gitsome/lib/github3/gists/history.py -> build/lib/gitsome/lib/github3/gists
  creating build/lib/gitsome/lib/github3/issues
  copying gitsome/lib/github3/issues/__init__.py -> build/lib/gitsome/lib/github3/issues
  copying gitsome/lib/github3/issues/comment.py -> build/lib/gitsome/lib/github3/issues
  copying gitsome/lib/github3/issues/event.py -> build/lib/gitsome/lib/github3/issues
  copying gitsome/lib/github3/issues/issue.py -> build/lib/gitsome/lib/github3/issues
  copying gitsome/lib/github3/issues/label.py -> build/lib/gitsome/lib/github3/issues
  copying gitsome/lib/github3/issues/milestone.py -> build/lib/gitsome/lib/github3/issues
  creating build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/__init__.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/branch.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/comment.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/commit.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/comparison.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/contents.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/deployment.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/hook.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/issue_import.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/pages.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/release.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/repo.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/stats.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/status.py -> build/lib/gitsome/lib/github3/repos
  copying gitsome/lib/github3/repos/tag.py -> build/lib/gitsome/lib/github3/repos
  creating build/lib/gitsome/lib/github3/search
  copying gitsome/lib/github3/search/__init__.py -> build/lib/gitsome/lib/github3/search
  copying gitsome/lib/github3/search/code.py -> build/lib/gitsome/lib/github3/search
  copying gitsome/lib/github3/search/issue.py -> build/lib/gitsome/lib/github3/search
  copying gitsome/lib/github3/search/repository.py -> build/lib/gitsome/lib/github3/search
  copying gitsome/lib/github3/search/user.py -> build/lib/gitsome/lib/github3/search
  creating build/lib/tests/data
  copying tests/data/__init__.py -> build/lib/tests/data
  copying tests/data/email.py -> build/lib/tests/data
  copying tests/data/emoji.py -> build/lib/tests/data
  copying tests/data/events.py -> build/lib/tests/data
  copying tests/data/gitignores.py -> build/lib/tests/data
  copying tests/data/issue.py -> build/lib/tests/data
  copying tests/data/license.py -> build/lib/tests/data
  copying tests/data/markdown.py -> build/lib/tests/data
  copying tests/data/thread.py -> build/lib/tests/data
  copying tests/data/trends.py -> build/lib/tests/data
  copying tests/data/user.py -> build/lib/tests/data
  copying tests/data/user_feed.py -> build/lib/tests/data
  running build_scripts
  creating build/scripts-3.6
  copying and adjusting scripts/xonsh -> build/scripts-3.6
  copying scripts/xonsh.bat -> build/scripts-3.6
  copying and adjusting scripts/gitsome -> build/scripts-3.6
  copying scripts/gitsome.bat -> build/scripts-3.6
  changing mode of build/scripts-3.6/xonsh from 644 to 755
  changing mode of build/scripts-3.6/xonsh.bat from 644 to 755
  changing mode of build/scripts-3.6/gitsome from 644 to 755
  changing mode of build/scripts-3.6/gitsome.bat from 644 to 755
  installing to build/bdist.macosx-10.12-x86_64/wheel
  running install
  Remove xonsh/parser_table.py
  Building lexer and parser tables.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 129, in <module>
      main()
    File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 122, in main
      setup(**skw)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 44, in run
      build_tables()
    File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 37, in build_tables
      outputdir='xonsh')
    File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/xonsh/parser.py", line 233, in __init__
      self.parser = yacc.yacc(**yacc_kwargs)
    File "/usr/local/lib/python3.6/site-packages/ply/yacc.py", line 3426, in yacc
      raise YaccError('Unable to build parser')
  ply.yacc.YaccError: Unable to build parser

  ----------------------------------------
  Failed building wheel for gitsome
  Running setup.py clean for gitsome
Failed to build gitsome
Installing collected packages: gitsome
  Running setup.py install for gitsome ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-03ruoaal-record/install-record.txt --single-version-externally-managed --compile:

    running install
    Building lexer and parser tables.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 129, in <module>
        main()
      File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 122, in main
        setup(**skw)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 44, in run
        build_tables()
      File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py", line 37, in build_tables
        outputdir='xonsh')
      File "/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/xonsh/parser.py", line 233, in __init__
        self.parser = yacc.yacc(**yacc_kwargs)
      File "/usr/local/lib/python3.6/site-packages/ply/yacc.py", line 3426, in yacc
        raise YaccError('Unable to build parser')
    ply.yacc.YaccError: Unable to build parser

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-03ruoaal-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/l9/06gllkm53ln9zsd3hznpw61r0000gn/T/pip-build-9sw_n_l4/gitsome/
```

**Comment by planktonfun** [comment]
After Installation it messed up my path
`$ bash: composer: command not found`
used
`$ pip3 install git+https://github.com/donnemartin/gitsome.git`
I have to reinstall composer in order to run it again

**Comment by donnemartin** [comment]
@Vinoth7: This installation issue looks the same as https://github.com/donnemartin/gitsome/issues/105.  I'll close this as a duplicate, let's track the issue going forward with https://github.com/donnemartin/gitsome/issues/105.

@planktonfun: Did `gitsome` install properly or did you receive the same error `ply.yacc.YaccError: Unable to build parser`?

**Comment by planktonfun** [comment]
Uninstalled and install gitsome again to replicate the results here they are:
`Collecting git+https://github.com/donnemartin/gitsome.git
  Cloning https://github.com/donnemartin/gitsome.git to c:\users\pau\appdata\local\temp\pip-acyrp6br-build
Requirement already satisfied (use --upgrade to upgrade): numpydoc<1.0,>=0.5 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): ply<4.0,>=3.4 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit<1.1.0,>=1.0.0 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): requests<3.0.0,>=2.8.1 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): colorama<1.0.0,>=0.3.3 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=5.1 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): pygments<3.0.0,>=2.0.2 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): feedparser<6.0.0,>=5.2.1 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): pytz<2017.0,>=2016.3 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): docopt<1.0.0,>=0.6.2 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): uritemplate.py<4.0.0,>=1.0.0 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from prompt-toolkit<1.1.0,>=1.0.0->gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from prompt-toolkit<1.1.0,>=1.0.0->gitsome==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): uritemplate>=2.0 in c:\users\pau\appdata\local\programs\python\python35-32\lib\site-packages (from uritemplate.py<4.0.0,>=1.0.0->gitsome==0.6.0)
Installing collected packages: gitsome
  Running setup.py install for gitsome: started
    Running setup.py install for gitsome: finished with status 'done'
Successfully installed gitsome-0.6.0
`
suprisingly composer still works after installation this time

**Comment by Vinoth7** [comment]
@planktonfun thank. hope it will be resolved asap.
