### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5f/2cz5l0fd4rvgvtjq0wbqskc00000gp/T/pip-build-QAUTM1/lxml/

### ISSUE THREAD

**Issue by HifzaK** [donnemartin/gitsome#126]
I am trying to install lxml on Mac and getting the following error.  Can anyone help me with this error? Thanks.

Collecting lxml
  Using cached lxml-3.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Building lxml version 3.8.0.
    Latest version of zlib is 1.2.11
    Downloading zlib into libs/zlib-1.2.11.tar.gz
    Unpacking zlib-1.2.11.tar.gz into build/tmp
    Latest version of libiconv is 1.15
    Downloading libiconv into libs/libiconv-1.15.tar.gz
    Unpacking libiconv-1.15.tar.gz into build/tmp
    Latest version of libxml2 is 2.9.4
    Downloading libxml2 into libs/libxml2-2.9.4.tar.gz
    Unpacking libxml2-2.9.4.tar.gz into build/tmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5f/2cz5l0fd4rvgvtjq0wbqskc00000gp/T/pip-build-QAUTM1/lxml/setup.py", line 233, in <module>
        **setup_extra_options()
      File "/private/var/folders/5f/2cz5l0fd4rvgvtjq0wbqskc00000gp/T/pip-build-QAUTM1/lxml/setup.py", line 144, in setup_extra_options
        STATIC_CFLAGS, STATIC_BINARIES)
      File "setupinfo.py", line 65, in ext_modules
        multicore=OPTION_MULTICORE)
      File "buildlibxml.py", line 359, in build_libxml2xslt
        libxslt_dir  = unpack_tarball(download_libxslt(download_dir, libxslt_version), build_dir)
      File "buildlibxml.py", line 195, in download_libxslt
        version_re, filename, version=version)
      File "buildlibxml.py", line 218, in download_library
        fns = ftp_listdir(location)
      File "buildlibxml.py", line 137, in ftp_listdir
        with closing(urlopen(url)) as res:
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
        return opener.open(url)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
        return getattr(self, name)(url)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 558, in open_ftp
        (fp, retrlen) = self.ftpcache[key].retrfile(file, type)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 926, in retrfile
        conn, retrlen = self.ftp.ntransfercmd(cmd)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 334, in ntransfercmd
        host, port = self.makepasv()
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 312, in makepasv
        host, port = parse227(self.sendcmd('PASV'))
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 830, in parse227
        raise error_reply, resp
    IOError: [Errno ftp error] 200 Switching to ASCII mode.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5f/2cz5l0fd4rvgvtjq0wbqskc00000gp/T/pip-build-QAUTM1/lxml/

**Comment by donnemartin** [comment]
Hi @HifzaK, this is not an error I've seen before and unfortunately I'm not able to reproduce it.  Not sure if this is related: https://github.com/donnemartin/gitsome/issues/4

**Comment by donnemartin** [comment]
Also, is this somehow related to the `gitsome` project?

**Comment by smrutiranjantripathy** [comment]
I'm facing the same issue !!!

**Comment by zhaopei8948** [comment]
same issue

**Comment by daoanhnhat1995** [comment]
I was able to reproduce this with the same error message.
`python3 --version` : `3.6.3`
`error`: `Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-0xm_hkv5/gitsome`

**Comment by mighty-pirate** [comment]
I get the same error when I try to install using ```pip 9.0.1``` and ```python 3.6.4``` but before that the message ```gitsome currently requires Python 3.4 or 3.5``` is printed to the terminal, so this might be the problem.

**Comment by donnemartin** [comment]
@mighty-pirate thanks for pointing that out, currently Python 3.6 is not supported, see: https://github.com/donnemartin/gitsome/issues/105

**Comment by rsurjano** [comment]
same issue in Python 3.4

**Comment by donnemartin** [comment]
Hi all, check out https://github.com/donnemartin/gitsome/pull/160, gitsome now supports Python 3.7.

Uploaded to PyPI: https://pypi.org/project/gitsome/
