### ISSUE TITLE
Homebrew package on macOS

### ISSUE THREAD

**Issue by techdragon** [donnemartin/gitsome#136]
It would be much easier to install this using homebrew to avoid polluting my day to day system python, it would be walled off over in homebrew. Then I could stop worrying and just `brew install gitsome` and `brew upgrade gitsome` and move on with life. I shouldn't need a hypervisor to run a simple command line program.

https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md

If I have time I might write the formula myself, this is just a chance for someone else to beat me to it.

**Comment by donnemartin** [comment]
Thanks for the suggestion!

**Comment by danielcr10** [comment]
Have any plans to support this?

**Comment by donnemartin** [comment]
Anyone want to hop on this with a PR?

**Comment by smorimoto** [comment]
Maybe I can help, I will check tomorrow.

**Comment by smorimoto** [comment]
Hmm...

```
Traceback (most recent call last):
  File "/usr/local/bin/gh", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/gitsome/0.8.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/Cellar/gitsome/0.8.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/gitsome/0.8.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/gitsome/0.8.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/gitsome/0.8.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/gitsome/0.8.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'uritemplate.py<4.0.0,>=1.0.0' distribution was not found and is required by gitsome
```

**Comment by smorimoto** [comment]
OK fixed. I will write a test and create a PR.

**Comment by smorimoto** [comment]
I submitted a PR.
