### ISSUE TITLE
flask-mysqldb install in mac-Unable to insatll 

### ISSUE THREAD

**Issue by darshanddd7** [donnemartin/gitsome#145]
Darshans-MacBook-Air:CrudWithFlask-4 ddd$ pip3 install Flask-Mysqldb
Collecting Flask-Mysqldb
  Using cached Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Flask-Mysqldb)
Collecting mysqlclient (from Flask-Mysqldb)
  Using cached mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup_posix.py", line 54, in get_config
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup_posix.py", line 54, in <listcomp>
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup_posix.py", line 12, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/

**Comment by donnemartin** [comment]
Hi @darshanddd7 is this related to gitsome?
