### ISSUE TITLE
Notifications are failing

### ISSUE THREAD

**Issue by j-a-m-l** [donnemartin/gitsome#154]
I've tried the latest Docker version and the Ubuntu/Debian package (0.7), but in both cases, I can't access the notifications:

```
$ gh notifications
Traceback (most recent call last):
  File "/usr/local/bin/gh", line 9, in <module>
    load_entry_point('gitsome', 'console_scripts', 'gh')()
  File "/gitsome/gitsome/main_cli.py", line 26, in cli
    github.cli()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/gitsome/gitsome/githubcli.py", line 486, in notifications
    github.notifications(limit, pager)
  File "/gitsome/gitsome/github.py", line 102, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/gitsome/gitsome/github.py", line 538, in notifications
    url = self.formatter.format_issues_url_from_thread(thread)
  File "/gitsome/gitsome/formatter.py", line 470, in format_issues_url_from_thread
    issue_id = url_parts[7]
IndexError: list index out of range
```

**Comment by donnemartin** [comment]
Hi @j-a-m-l, I'm not able to reproduce this, can you try the latest version if it's failing there?

**Comment by Pranay144** [comment]
There is no class for "notification" in notification.py file.
I can add it!
If this issue is still needs work!
