### ISSUE TITLE
ValueError: Could not translate ANSI color code '01;05;37;41' into a known color in the palette

### ISSUE THREAD

**Issue by unixc3t** [donnemartin/gitsome#164]
```bash
[rudy@rudy-kde ~]$ gitsome
Gitsome Version: 0.8.4
Traceback (most recent call last):
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/main.py", line 404, in main
    args = premain(argv)
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/main.py", line 289, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/execer.py", line 62, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/built_ins.py", line 1272, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/built_ins.py", line 1348, in load
    self.env = Env(default_env())
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/environ.py", line 1337, in __init__
    self[key] = val
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/environ.py", line 1499, in __setitem__
    val = ensurer.convert(val)
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/environ.py", line 445, in convert
    return cls.fromstring(x)
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/environ.py", line 408, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/home/rudy/.pyenv/versions/3.7.3/lib/python3.7/site-packages/xonsh/ansi_colors.py", line 268, in ansi_color_escape_code_to_name
    msg.format(escape_code=escape_code, names=names, name=name, n=n)
ValueError: Could not translate ANSI color code '01;05;37;41' into a known color in the palette. Specifically, the 'BOLD_SLOWBLINK_WHITE' portion of 'WHITE' in ['BOLD_', 'SLOWBLINK_', 'WHITE', 'BACKGROUND_RED'] seems to missing.
Xonsh encountered an issue during launch
Failback to /bin/sh
sh-5.0$ 

```

**Comment by unixc3t** [comment]
```bash
echo $LS_COLORS
rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.pdf=00;32:*.ps=00;32:*.txt=00;32:*.patch=00;32:*.diff=00;32:*.log=00;32:*.tex=00;32:*.doc=00;32:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:

```

**Comment by unixc3t** [comment]
install [https://github.com/trapd00r/LS_COLORS](url) solve this problem
