### ISSUE TITLE
No module named 'prompt_toolkit.key_binding.manager'

### ISSUE THREAD

**Issue by rutkai** [donnemartin/gitsome#173]
Hi,

I just installed gitsome but right after a successful install it cannot start:

```
rutkai@virtual:~$ gitsome
Gitsome Version: 0.8.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/xonsh/main.py", line 404, in main
    args = premain(argv)
  File "/usr/local/lib/python3.7/dist-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.7/dist-packages/xonsh/main.py", line 304, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/xonsh/shell.py", line 197, in __init__
    from xonsh.ptk.shell import PromptToolkitShell as shell_class
  File "/usr/local/lib/python3.7/dist-packages/xonsh/ptk/shell.py", line 6, in <module>
    from prompt_toolkit.key_binding.manager import KeyBindingManager
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.manager'
Xonsh encountered an issue during launch
Failback to /bin/sh
$
```

Install output:

```
rutkai@virtual ~ $ sudo pip3 install gitsome
Collecting gitsome
  Downloading https://files.pythonhosted.org/packages/6a/8a/5a10cb1bcc64eacdb343b5241f4bad32faa46e1cee26c5728ce8846dadcb/gitsome-0.8.4.tar.gz (609kB)
    100% |████████████████████████████████| 614kB 1.9MB/s 
Collecting click<7.0,>=5.1 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 4.8MB/s 
Requirement already satisfied: colorama<1.0.0,>=0.3.3 in /usr/local/lib/python3.7/dist-packages (from gitsome) (0.4.1)
Collecting docopt<1.0.0,>=0.6.2 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting feedparser<6.0.0,>=5.2.1 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2 (192kB)
    100% |████████████████████████████████| 194kB 3.1MB/s 
Collecting numpydoc<1.0,>=0.5 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/b0/70/4d8c3f9f6783a57ac9cc7a076e5610c0cc4a96af543cafc9247ac307fbfe/numpydoc-0.9.2.tar.gz
Requirement already satisfied: ply<4.0,>=3.4 in /usr/lib/python3/dist-packages (from gitsome) (3.11)
Collecting prompt_toolkit<2.1.0,>=2.0.0 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 2.8MB/s 
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in /usr/lib/python3/dist-packages (from gitsome) (2.3.1)
Collecting pytz<2017.0,>=2016.3 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/f5/fa/4a9aefc206aa49a4b5e0a72f013df1f471b4714cdbe6d78f0134feeeecdb/pytz-2016.10-py2.py3-none-any.whl (483kB)
    100% |████████████████████████████████| 491kB 3.6MB/s 
Requirement already satisfied: requests<3.0.0,>=2.8.1 in /usr/lib/python3/dist-packages (from gitsome) (2.21.0)
Collecting uritemplate.py<4.0.0,>=1.0.0 (from gitsome)
  Downloading https://files.pythonhosted.org/packages/8b/ba/6cbb9c3bf4f53997d8d1f69414fc7962f536ba43d283f0e32de68534f6a4/uritemplate.py-3.0.2-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 3.5MB/s 
Collecting sphinx>=1.6.5 (from numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/61/10/2138f720007bb501e546f19057588a4ed88ccbed3c006f6edb693f1e8053/Sphinx-2.4.2-py3-none-any.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 537kB/s 
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt_toolkit<2.1.0,>=2.0.0->gitsome) (1.12.0)
Requirement already satisfied: wcwidth in /usr/lib/python3/dist-packages (from prompt_toolkit<2.1.0,>=2.0.0->gitsome) (0.1.7)
Collecting uritemplate>=2.0 (from uritemplate.py<4.0.0,>=1.0.0->gitsome)
  Downloading https://files.pythonhosted.org/packages/bf/0c/60d82c077998feb631608dca3cc1fe19ac074e772bf0c24cf409b977b815/uritemplate-3.0.1-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.3->numpydoc<1.0,>=0.5->gitsome) (1.1.0)
Collecting snowballstemmer>=1.1 (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/7d/4b/cdf1113a0e88b641893b814e9c36f69a6fda28cd88b62c7f0d858cde3166/snowballstemmer-2.0.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 3.1MB/s 
Collecting sphinxcontrib-applehelp (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/13/9a/4428b3114d654cb1cd34d90d5e6fab938d5436f94a571155187ea1dd78b4/sphinxcontrib_applehelp-1.0.1-py2.py3-none-any.whl (121kB)
    100% |████████████████████████████████| 122kB 3.6MB/s 
Collecting sphinxcontrib-qthelp (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/ce/5b/4747c3ba98b3a3e21a66faa183d8f79b9ded70e74212a7988d236a6eb78a/sphinxcontrib_qthelp-1.0.2-py2.py3-none-any.whl (90kB)
    100% |████████████████████████████████| 92kB 4.3MB/s 
Collecting sphinxcontrib-jsmath (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl
Collecting imagesize (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/31/b2/b5522a0c8d11e4aff83f8342f3f0dea68c2fb25aa44403e420587f0ce204/imagesize-1.2.0-py2.py3-none-any.whl
Collecting sphinxcontrib-serializinghtml (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/57/b3/3648e48fa5682e61e9839d62de4e23af1795ceb738d68d73bd974257a95c/sphinxcontrib_serializinghtml-1.1.3-py2.py3-none-any.whl (89kB)
    100% |████████████████████████████████| 92kB 3.3MB/s 
Requirement already satisfied: docutils>=0.12 in /usr/local/lib/python3.7/dist-packages (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome) (0.15.2)
Collecting sphinxcontrib-htmlhelp (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/e4/35/80a67cc493f4a8a9634ab203a77aaa1b84d79ccb1c02eca72cb084d2c7f7/sphinxcontrib_htmlhelp-1.0.2-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 4.8MB/s 
Collecting babel!=2.0,>=1.3 (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/15/a1/522dccd23e5d2e47aed4b6a16795b8213e3272c7506e625f2425ad025a19/Babel-2.8.0-py2.py3-none-any.whl (8.6MB)
    100% |████████████████████████████████| 8.6MB 178kB/s 
Collecting sphinxcontrib-devhelp (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/b0/a3/fea98741f0b2f2902fbf6c35c8e91b22cd0dd13387291e81d457f9a93066/sphinxcontrib_devhelp-1.0.1-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 3.1MB/s 
Collecting packaging (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/98/42/87c585dd3b113c775e65fd6b8d9d0a43abe1819c471d7af702d4e01e9b20/packaging-20.1-py2.py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome) (41.1.0)
Collecting pyparsing>=2.0.2 (from packaging->sphinx>=1.6.5->numpydoc<1.0,>=0.5->gitsome)
  Downloading https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 4.5MB/s 
Building wheels for collected packages: gitsome, docopt, feedparser, numpydoc
  Running setup.py bdist_wheel for gitsome ... done
  Stored in directory: /root/.cache/pip/wheels/c0/e0/cf/50c9b29ddf13a2a1763557be6bb47a8dbaf9182a295da5aad0
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Running setup.py bdist_wheel for feedparser ... done
  Stored in directory: /root/.cache/pip/wheels/8c/69/b7/f52763c41c5471df57703a0ef718a32a5e81ee35dcf6d4f97f
  Running setup.py bdist_wheel for numpydoc ... done
  Stored in directory: /root/.cache/pip/wheels/96/f3/52/25c8e1f40637661d27feebc61dae16b84c7cdd93b8bc3d7486
Successfully built gitsome docopt feedparser numpydoc
Installing collected packages: click, docopt, feedparser, Jinja2, snowballstemmer, sphinxcontrib-applehelp, sphinxcontrib-qthelp, sphinxcontrib-jsmath, imagesize, sphinxcontrib-serializinghtml, sphinxcontrib-htmlhelp, pytz, babel, sphinxcontrib-devhelp, pyparsing, packaging, alabaster, sphinx, numpydoc, prompt-toolkit, uritemplate, uritemplate.py, gitsome
  Found existing installation: prompt-toolkit 1.0.15
    Not uninstalling prompt-toolkit at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'prompt-toolkit'. No files were found to uninstall.
Successfully installed Jinja2-2.11.1 alabaster-0.7.12 babel-2.8.0 click-6.7 docopt-0.6.2 feedparser-5.2.1 gitsome-0.8.4 imagesize-1.2.0 numpydoc-0.9.2 packaging-20.1 prompt-toolkit-2.0.10 pyparsing-2.4.6 pytz-2016.10 snowballstemmer-2.0.0 sphinx-2.4.2 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.2 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.3 uritemplate-3.0.1 uritemplate.py-3.0.2
```

```
rutkai@virtual ~ $ pip3 install prompt-toolkit
Requirement already satisfied: prompt-toolkit in /usr/local/lib/python3.7/dist-packages (2.0.10)
Requirement already satisfied: wcwidth in /usr/lib/python3/dist-packages (from prompt-toolkit) (0.1.7)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit) (1.12.0)
```

And the system is `Ubuntu 19.10`.

I installed it with sudo globally and `prompt_toolkit` is installed as well.

**Comment by rutkai** [comment]
It magically started working. :) Business as usual
