### ISSUE TITLE
Error when Running pip install :  python setup.py egg_info

### ISSUE THREAD

**Issue by awesomeo184** [donnemartin/gitsome#174]
I ensure pip, setuptools and wheel are up to date. I successfully installed one but get error while installing another one. please help

C:\Program Files (x86)\Python38-32>pip install beautifulsoup
Collecting beautifulsoup
  Downloading BeautifulSoup-3.2.2.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-4lnlu4ky\\beautifulsoup\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-4lnlu4ky\\beautifulsoup\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-4lnlu4ky\beautifulsoup\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-4lnlu4ky\beautifulsoup\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-4lnlu4ky\beautifulsoup\setup.py", line 3
        "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by awesomeo184** [comment]
![image](https://user-images.githubusercontent.com/63030569/116869084-05841900-ac4b-11eb-8b02-aaa6753293db.png)
