### ISSUE TITLE
Kali Linux - Problem

### ISSUE THREAD

**Issue by ghost** [donnemartin/gitsome#179]
pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
Collecting http://effbot.org/downloads/Imaging-1.1.6.tar.gz
  Downloading http://effbot.org/downloads/Imaging-1.1.6.tar.gz (435 kB)
     |████████████████████████████████| 435 kB 184 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-33c0dhzy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-33c0dhzy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-eb17y7mr                                                    
         cwd: /tmp/pip-req-build-33c0dhzy/                                 
    Complete output (6 lines):                                             
    Traceback (most recent call last):                                     
      File "<string>", line 1, in <module>                                 
      File "/tmp/pip-req-build-33c0dhzy/setup.py", line 175                
        print "--- using Tcl/Tk libraries at", TCL_ROOT                    
              ^                                                            
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("--- using Tcl/Tk libraries at", TCL_ROOT)?                               
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ghost** [comment]
And


python trity.py
Traceback (most recent call last):
  File "trity.py", line 27, in <module>
    from searchs import *
  File "trity/searchs.py", line 1, in <module>
    from google import search
ImportError: No module named google
