### ISSUE TITLE
prompt-toolkit

### ISSUE THREAD

**Issue by andrii482** [donnemartin/gitsome#185]
`ERROR: gitsome 0.8.4 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 3.0.9 which is incompatible.`

also, it I install required version - I get errors:
```Traceback (most recent call last):
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 419, in main
    args = premain(argv)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 308, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/shell.py", line 211, in __init__
    from xonsh.ptk_shell.shell import PromptToolkitShell as shell_class
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 26, in <module>
    from prompt_toolkit.key_binding.bindings.emacs import (
ImportError: cannot import name 'load_emacs_shift_selection_bindings' from 'prompt_toolkit.key_binding.bindings.emacs' (/usr/lib/python3/dist-packages/prompt_toolkit/key_binding/bindings/emacs.py)
Xonsh encountered an issue during launch
Failback to /bin/bash
Traceback (most recent call last):
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 419, in main
    args = premain(argv)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/main.py", line 308, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/shell.py", line 211, in __init__
    from xonsh.ptk_shell.shell import PromptToolkitShell as shell_class
  File "/home/andrii/.local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 26, in <module>
    from prompt_toolkit.key_binding.bindings.emacs import (
ImportError: cannot import name 'load_emacs_shift_selection_bindings' from 'prompt_toolkit.key_binding.bindings.emacs' (/usr/lib/python3/dist-packages/prompt_toolkit/key_binding/bindings/emacs.py)
Xonsh encountered an issue during launch
```

**Comment by rx-dev** [comment]
I'm also having issues with this, pip is struggling to handle newer versions w/ older versions and not all my packages will work due to gitsome needing an older version
