### ISSUE TITLE
Command create-repo results in NoneType conversion if no description is specified

### ISSUE THREAD

**Issue by Manu343726** [donnemartin/gitsome#49]
Similar to #40, but with `create-repo` command.

Full backtrace bellow:

```
Traceback (most recent call last):
  File "/usr/bin/gh", line 9, in <module>
    load_entry_point('gitsome==0.5.0', 'console_scripts', 'gh')()
  File "/usr/lib/python3.5/site-packages/gitsome/main_cli.py", line 26, in cli
    github.cli()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/gitsome/githubcli.py", line 147, in create_repo
    github.create_repo(repo_name, repo_desc, private)
  File "/usr/lib/python3.5/site-packages/gitsome/github.py", line 84, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/gitsome/github.py", line 232, in create_repo
    repo.description),
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by donnemartin** [comment]
Nice catch.  Interested in a PR?  I think the fix might be similar to https://github.com/donnemartin/gitsome/commit/64ce02e029beca1e3fb48bd009e53d4ae8301e26.
