### ISSUE TITLE
Error when installing gitsome via pip3

### ISSUE THREAD

**Issue by JoseCage** [donnemartin/gitsome#59]
Hello. I'm trying to install it in my Ubuntu 16.04 and it retrieve the code bellow.. 
I follow the instructions mentioned in #4 

(~) ➜ () ➜ sudo -H pip3 install gitsome

Collecting gitsome
  Using cached gitsome-0.6.0.tar.gz
Collecting numpydoc<1.0,>=0.5 (from gitsome)
  Using cached numpydoc-0.6.0.tar.gz
Collecting ply<4.0,>=3.4 (from gitsome)
  Using cached ply-3.8.tar.gz
Collecting prompt-toolkit<1.1.0,>=1.0.0 (from gitsome)
  Using cached prompt_toolkit-1.0.0-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests<3.0.0,>=2.8.1 in /usr/lib/python3/dist-packages (from gitsome)
Collecting colorama<1.0.0,>=0.3.3 (from gitsome)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting click<7.0,>=5.1 (from gitsome)
  Using cached click-6.6.tar.gz
Collecting pygments<3.0.0,>=2.0.2 (from gitsome)
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1006, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 695, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (feedparser 5.1.3 (/usr/lib/python3/dist-packages), Requirement.parse('feedparser<6.0.0,>=5.2.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by JoseCage** [comment]
Thanks. I Solve this running again:

`sudo pip3 install gitsome`

**Comment by donnemartin** [comment]
Thanks for the followup, glad it's working now.

Looked like the [`feedparser`](https://github.com/donnemartin/gitsome/blob/master/setup.py#L109) dependency didn't get properly upgraded from `5.1.3` to `5.2.1` (not sure why) when first running the `pip install` command.

**Comment by JoseCage** [comment]
Thanks for support.. I've installed and upgraded and now works fine..
