### ISSUE TITLE
UnicodeDecodeError: 'gbk' in windows 10

### ISSUE THREAD

**Issue by SizheCai** [donnemartin/gitsome#77]
C:\Users\xxxx>gitsome
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\subprocess.py", line 1283, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 3: illegal multibyte sequence

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\lib\site-packages\xonsh\main.py", line 112, in <module>
    main()
  File "C:\Program Files\Python35\lib\site-packages\xonsh\main.py", line 76, in main
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "C:\Program Files\Python35\lib\site-packages\xonsh\shell.py", line 27, in __init__
    self._init_environ(ctx)
  File "C:\Program Files\Python35\lib\site-packages\xonsh\shell.py", line 57, in _init_environ
    self.execer = Execer()
  File "C:\Program Files\Python35\lib\site-packages\xonsh\execer.py", line 40, in __init__
    load_builtins(execer=self)
  File "C:\Program Files\Python35\lib\site-packages\xonsh\built_ins.py", line 648, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env())
  File "C:\Program Files\Python35\lib\site-packages\xonsh\environ.py", line 676, in default_env
    issue_warning=False))
  File "C:\Program Files\Python35\lib\site-packages\xonsh\foreign_shells.py", line 205, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "C:\Program Files\Python35\lib\site-packages\xonsh\foreign_shells.py", line 71, in foreign_shell_data
    universal_newlines=True)
  File "C:\Program Files\Python35\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python35\lib\subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Program Files\Python35\lib\subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Program Files\Python35\lib\subprocess.py", line 1333, in _communicate
    stdout = stdout[0]
IndexError: list index out of range

![gbk3](https://cloud.githubusercontent.com/assets/19942117/18122147/9c83bd9e-6f9a-11e6-809d-0ca6673164a4.png)

 #I am Chinese user

**Comment by donnemartin** [comment]
Hi @SizheCai, it looks like this is an error on startup?

What is the output of:

    $ pip freeze

Also this exception seems to be in the `xonsh` code.  Curious if `xonsh` works on your system?  Here are the Windows setup instructions:

http://xon.sh/windows.html

There's a section there about Unicode support on Windows that might also be helpful:

http://xon.sh/windows.html#unicode-support-for-windows

**Comment by donnemartin** [comment]
Hi @SizheCai, I'm closing this issue due to inactivity.  If you're still seeing an issue please respond to my previous message, thanks!
